spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ideabox?serverTimezone=UTC
    username: user
    password: root
  jpa:
    properties:
      hibernate:
      diaclect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 7000